### ISSUE TITLE
Umverlegen der API-Logik in Extra-Klassen

### ISSUE THREAD

**Issue by HonKLam** [HonKLam/fishdex#21]
Einige Codestellen wiederholen sich in der API Logik (sowas wie speichere den Fisch, etc.) und man könnte das gut in eine extra Klasse verlegen für mehr Übersicht.

- [x] FishService erstellen
- [x] die API Logik aus FishController in FishService packen
- [x] FishService in FishController referenzieren
- [x] iwen aus Backend fragen ob das noch für Catch / Diary gemacht werden kann

**Comment by Petan-s** [comment]
LGTM
