### ISSUE TITLE
(Prototyp)-Designs + weitere Entwürfe fertig/vorzeigbar

### ISSUE THREAD

**Issue by HonKLam** [HonKLam/fishdex#3]
### Ziel
Design für 2 Seiten erstellen. Sie müssen noch nicht vollständig fertig sein, aber schon in die grobe Richtung gehen.

- [x] Seite zum Eintragen von neuer FischART (Formular, also Name der Fischart, Ort, Wasser, ... -> das soll man asufüllen können und das ist dann eine Fischart im Fishdex, später können wir dann einen Fang-Eintrag machen, der diese Fischart auswählt)
- [x] Seite zum Darstellen aller Fischearten, die bisher eingetragen worden (der "Fishdex")
- [x] Weitere Entwürfe für andere Features sind schon gemacht

**Comment by HonKLam** [comment]
@FeGii Ich hab nochmal deine Aufgabe überarbeitet. Ich würde gerne erstmal ein Formular für die FischART haben, die dann im Fishdex (der Seite wo alle FischARTEN angezeigt werden) angezeigt werden. Hoffe, dass ich jz noch nicht zu spät dran bin...

**Comment by FeGii** [comment]
@HonKLam  Alles gut, mache ich dir fertig.
